In [13]:
import numpy as np
from sklearn.decomposition import NMF

In [19]:
X = [
        [1, 0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [1, 0, 0, 1, 0, 0],
        [0, 1, 0, 0, 1, 0],
        [1, 0, 1, 0, 0, 1]
    ]

In [20]:
nmf = NMF(n_components=3)
nmf.fit(X)

c:\users\tatsuki\appdata\local\programs\python\python38\lib\site-packages\sklearn\decomposition\_nmf.py:312: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  warnings.warn(("The 'init' value, when 'init=None' and "


NMF(n_components=3)

In [21]:
W = nmf.fit_transform(X)
print(np.round(W, 1))

[[0.9 0.  0. ]
 [0.  0.7 0. ]
 [0.  0.  0.6]
 [0.9 0.  0. ]
 [0.  1.1 0. ]
 [0.1 0.  1.2]]


c:\users\tatsuki\appdata\local\programs\python\python38\lib\site-packages\sklearn\decomposition\_nmf.py:312: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  warnings.warn(("The 'init' value, when 'init=None' and "


In [22]:
H = nmf.components_
print(np.round(H, 1))

[[1.1 0.  0.  1.1 0.  0. ]
 [0.  1.1 0.  0.  0.7 0. ]
 [0.6 0.  1.  0.  0.  0.7]]


In [23]:
# 行列Wと行列Hの積が行列Xになるか確かめる
WH = np.dot(W, H)
print(np.round(WH, 1))

[[1.  0.  0.  1.  0.  0. ]
 [0.  0.7 0.  0.  0.4 0. ]
 [0.3 0.  0.6 0.  0.  0.4]
 [1.  0.  0.  1.  0.  0. ]
 [0.  1.2 0.  0.  0.7 0. ]
 [0.9 0.  1.2 0.2 0.  0.8]]
